// Chat Room constants

export const CREATE_CHAT_ROOM_REQUEST = 'rooms/CREATE_CHAT_ROOM_REQUEST';
export const CREATE_CHAT_ROOM_SUCCESS = 'rooms/CREATE_CHAT_ROOM_SUCCESS';
export const CREATE_CHAT_ROOM_FAIL = 'rooms/CREATE_CHAT_ROOM_FAIL';

export const GET_CHAT_ROOM_REQUEST = 'rooms/GET_CHAT_ROOM_REQUEST';
export const SET_CHAT_ROOM_SUCCESS = 'rooms/SET_CHAT_ROOM_SUCCESS';
export const GET_CHAT_ROOM_DETAIL = 'rooms/GET_CHAT_ROOM_DETAIL';
export const GET_CHAT_ROOM_FAIL = 'rooms/GET_CHAT_ROOM_FAIL';
export const GET_CHAT_ROOM_RESET = 'rooms/GET_CHAT_ROOM_RESET';

export const GET_ROOM_COUNT = 'rooms/GET_ROOM_COUNT'
export const SET_ROOMS_COUNT = 'rooms/SET_ROOMS_COUNT'

export const GET_ALL_ROOMS_REQUEST = 'rooms/GET_ALL_ROOMS_REQUEST';
export const SET_ALL_ROOMS_SUCCESS = 'rooms/SET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS = 'rooms/GET_ALL_ROOMS';
export const GET_ALL_ROOMS_FAIL = 'rooms/GET_ALL_ROOMS_FAIL';
export const GET_ALL_ROOMS_RESET = 'rooms/GET_ALL_ROOMS_RESET';

export const UPDATE_CHAT_ROOM_REQUEST = 'rooms/UPDATE_CHAT_ROOM_REQUEST';
export const UPDATE_CHAT_ROOM_SUCCESS = 'rooms/UPDATE_CHAT_ROOM_SUCCESS';
export const UPDATE_CHAT_ROOM_FAIL = 'rooms/UPDATE_CHAT_ROOM_FAIL';
export const UPDATE_CHAT_ROOM_RESET = 'rooms/UPDATE_CHAT_ROOM_RESET';

export const DELETE_CHAT_ROOM_REQUEST = 'rooms/DELETE_CHAT_ROOM_REQUEST';
export const DELETE_CHAT_ROOM_SUCCESS = 'rooms/DELETE_CHAT_ROOM_SUCCESS';
export const DELETE_CHAT_ROOM_FAIL = 'rooms/DELETE_CHAT_ROOM_FAIL';
export const DELETE_CHAT_ROOM_RESET = 'rooms/DELETE_CHAT_ROOM_RESET';